# Synthetic Data Generation on the German Credit Risk Dataset

## Introduction

In this notebook we focus on the generation of synthetic data by leveraging the models trained in the previous steps. Each trained model is loaded from its saved state and used to produce synthetic samples of the German Credit Risk dataset.

These generated datasets will then serve as the foundation for the upcoming evaluation phase.

## 0 Imports and function definition

In this notebook we import the essential libraries required for loading the trained models and generating synthetic data. These include pandas for data handling, pickle for loading saved models, and the corresponding packages for each generative approach (GReaT and SDV synthesizers).

### Downloads

In [1]:
!pip install be_great peft==0.9.0 sdv

Collecting be_great
  Downloading be_great-0.0.9-py3-none-any.whl.metadata (5.8 kB)
Collecting peft==0.9.0
  Downloading peft-0.9.0-py3-none-any.whl.metadata (13 kB)
Collecting sdv
  Downloading sdv-1.24.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (2.6.0+cu124)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (4.53.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (1.8.1)
Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (0.5.3)
Requirement already satisfied: huggingface-hub>=0.17.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (0.33.4)
Requirement already satisfied: datasets>=2.5.2 in /usr/local/lib/python3.11/dist-packages (from be_great) (2.14.4)
Requirement already satisfied: pandas>=1.4.4 in /usr/local/lib/python3.11/dist-packages (from be_great) (2.2.2)
Requirement already satisfied: scikit_learn>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from be_great) (1.6.1)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.39.9-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.39.9-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from sdv) (3.1.1)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from sdv) (0.21)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.12.3-py3-none-any.whl.metadata (9.5 kB)
Collecting ctgan>=0.11.0 (from sdv)
  Downloading ctgan-0.11.0-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting rdt>=1.17.0 (from sdv)
  Downloading rdt-1.17.1-py3-none-any.whl.metadata (10 kB)
Collecting sdmetrics>=0.21.0 (from sdv)
  Downloading sdmetrics-0.21.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.11/dist-packages (from sdv) (4.3.8)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.13.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.4.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.11/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.11/dist-packages (from copulas>=0.12.1->sdv) (1.15.3)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (0.3.7)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets>=2.5.2->be_great) (2025.3.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (3.11.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (1.1.5)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.4->be_great) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.4->be_great) (2025.2)
Collecting Faker>=17 (from rdt>=1.17.0->sdv)
  Downloading faker-37.4.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn>=1.1.1->be_great) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn>=1.1.1->be_great) (3.6.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft==0.9.0) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers->peft==0.9.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers->peft==0.9.0) (0.21.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.20.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (8.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (2025.7.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.13.0->peft==0.9.0) (3.0.2)
Downloading peft-0.9.0-py3-none-any.whl (190 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 8.5 MB/s eta 0:00:00
Downloading be_great-0.0.9-py3-none-any.whl (19 kB)
Downloading sdv-1.24.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 17.9 MB/s eta 0:00:00
Downloading boto3-1.39.9-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 14.6 MB/s eta 0:00:00
Downloading botocore-1.39.9-py3-none-any.whl (13.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 94.5 MB/s eta 0:00:00
Downloading copulas-0.12.3-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 5.4 MB/s eta 0:00:00
Downloading ctgan-0.11.0-py3-none-any.whl (24 kB)
Downloading deepecho-0.7.0-py3-none-any.whl (27 kB)
Downloading rdt-1.17.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 7.5 MB/s eta 0:00:00
Downloading sdmetrics-0.21.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.5/193.5 kB 19.3 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 112.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 91.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 58.9 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 19.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 54.8 MB/s eta 0:00:00
Downloading faker-37.4.2-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 50.8 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.13.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.3/85.3 kB 9.2 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, jmespath, Faker, nvidia-cusparse-cu12, nvidia-cudnn-cu12, botocore, s3transfer, rdt, nvidia-cusolver-cu12, copulas, sdmetrics, boto3, deepecho, ctgan, sdv, peft, be_great
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: peft
    Found existing installation: peft 0.16.0
    Uninstalling peft-0.16.0:
      Successfully uninstalled peft-0.16.0
Successfully installed Faker-37.4.2 be_great-0.0.9 boto3-1.39.9 botocore-1.39.9 copulas-0.12.3 ctgan-0.11.0 deepecho-0.7.0 jmespath-1.0.1 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 peft-0.9.0 rdt-1.17.1 s3transfer-0.13.1 sdmetrics-0.21.0 sdv-1.24.1

### Imports

In [2]:
import pandas as pd
import os
from be_great import GReaT
from sdv.single_table import TVAESynthesizer, CTGANSynthesizer, CopulaGANSynthesizer
from sdv.metadata import SingleTableMetadata
import pickle

In [3]:
os.environ["WANDB_DISABLED"] = "true" #to avoid the requests from WANDB

### Functions definitions

The function load_model is a simple utility that loads a previously saved generative model from disk using pickle. By providing the file path, it restores the model object into memory, making it ready for use in data generation.

In [4]:
def load_model(file_path):
  with(open(file_path, 'rb')) as f:
    model = pickle.load(f)
  return model

These functions define a unified interface for generating synthetic data with the trained models. Each function takes as input a generative model and the desired number of rows, then calls the model’s sampling method to produce a synthetic dataset. While the SDV-based models (CopulaGAN, TVAE, CTGAN) use sample(num_rows=...), the GReaT-based models rely on sample(n_samples=..., max_length=...) to account for text-based generation constraints.

In [5]:
def create_synthetic_data_CopulaGAN(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [6]:
def create_synthetic_data_TVAE(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [7]:
def create_synthetic_data_CTGAN(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [8]:
def create_synthetic_data_distil_GReaT(model, num_rows):
    synthetic_data = model.sample(n_samples=num_rows, max_length=2000, guided_sampling=True)
    return synthetic_data

In [9]:
def create_synthetic_data_GReaT(model, num_rows):
    synthetic_data = model.sample(n_samples=num_rows, max_length=2000, guided_sampling=True)
    return synthetic_data

## 1 Sampling

We now move to the sampling phase, where synthetic records are generated from the trained models. To ensure a fair comparison in the upcoming evaluations, we fix the number of generated rows to 1,000, which matches the size of the original German Credit Risk dataset.

For each model, the workflow follows the same steps:

Load the pre-trained model from file.

Generate synthetic data with the specified number of rows.

Display a preview of the generated dataset.

Save the synthetic records into a CSV file for later use.

This process is applied consistently across all models (CopulaGAN, TVAE, CTGAN, GReaT, and distil-GReaT).

In [10]:
num_rows = 1000

### CopulaGAN

In [11]:
model_CopulaGAN = load_model('copulagan_german.pkl')

In [12]:
synthetic_data_CopulaGAN = create_synthetic_data_CopulaGAN(model_CopulaGAN, num_rows)

In [13]:
synthetic_data_CopulaGAN.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,28.0,female,2,rent,little,rich,6135.0,56.0,furniture/equipment,good
1,59.0,male,3,own,little,Unknown,1740.0,11.0,radio/TV,bad
2,22.0,male,2,own,little,little,2156.0,27.0,car,good
3,25.0,male,2,own,little,moderate,1215.0,17.0,furniture/equipment,good
4,49.0,male,2,own,little,moderate,10546.0,14.0,furniture/equipment,bad

In [14]:
synthetic_data_CopulaGAN.to_csv('synthetic_data_german_CopulaGAN.csv', index=False)

### TVAE

In [15]:
model_TVAE = load_model('tvae_german.pkl')

In [16]:
synthetic_data_TVAE = create_synthetic_data_TVAE(model_TVAE, num_rows)

In [17]:
synthetic_data_TVAE.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,24.0,male,2,own,little,Unknown,1683.0,13.0,radio/TV,good
1,27.0,female,2,own,little,little,1157.0,11.0,furniture/equipment,bad
2,22.0,male,2,own,little,Unknown,5067.0,24.0,radio/TV,good
3,25.0,male,2,own,little,little,5978.0,39.0,car,bad
4,29.0,male,2,own,little,Unknown,1148.0,6.0,radio/TV,good

In [18]:
synthetic_data_TVAE.to_csv('synthetic_data_german_TVAE.csv', index=False)

### CTGAN

In [19]:
model_CTGAN = load_model('ctgan_german.pkl')

In [20]:
synthetic_data_CTGAN = create_synthetic_data_CTGAN(model_CTGAN, num_rows)

In [21]:
synthetic_data_CTGAN.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,24.0,male,2,own,Unknown,rich,1513.0,4.0,radio/TV,good
1,57.0,male,3,own,little,moderate,3554.0,4.0,radio/TV,good
2,31.0,male,2,own,quite rich,Unknown,1465.0,9.0,business,bad
3,66.0,male,2,rent,little,Unknown,3315.0,18.0,radio/TV,good
4,75.0,male,1,own,little,little,250.0,5.0,radio/TV,good

In [22]:
synthetic_data_CTGAN.to_csv('synthetic_data_german_CTGAN.csv', index=False)

### Distil-GReaT

In [23]:
model_distil_GReaT = load_model('distil_GReaT_german.pkl')

In [24]:
synthetic_data_distil_GReaT = create_synthetic_data_distil_GReaT(model_distil_GReaT, num_rows)

100%|██████████| 1000/1000 [36:35<00:00,  2.20s/it]

In [25]:
synthetic_data_distil_GReaT.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,34.0,male,2.0,own,little,Unknown,966.0,18.0,car,good
1,51.0,male,2.0,ownThe,Unknown,little,618.0,18.0,business,bad
2,41.0,male,2.0,ownWhat,little,little,2630.0,12.0,furniture/equipment,good
3,28.0,male,2.0,own,little,Unknown,942.0,12.0,radio/TV,good
4,26.0,female,3.0,own,littleA group of young men are taking shelter ...,moderate,1579.0,12.0,furniture/equipment,good

In [26]:
synthetic_data_distil_GReaT.to_csv('synthetic_data_german_distil_GReaT.csv', index=False)

GReaT

In [27]:
model_GReaT = load_model('GReaT_german.pkl')

In [28]:
synthetic_data_GReaT = create_synthetic_data_GReaT(model_GReaT, num_rows)

100%|██████████| 1000/1000 [1:02:45<00:00,  3.77s/it]

In [29]:
synthetic_data_GReaT.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,40.0,femaleA new report from the National Institute...,2,own,little,UnknownHow do you use your desktop computer,1282.0,18.0,radio/TV,good
1,33.0,male,2,own,little,Unknown,1282.0,36.0,car,bad
2,62.0,male,2,own,little,littleIf you're shopping for a car,4397.0,18.0,car,good
3,37.0,male,2,free,little,little,2680.0,9.0,radio/TV,bad
4,51.0,female,2,rent,moderateThe following article is from the Dece...,moderate,1178.0,12.0,furniture/equipment,good

In [30]:
synthetic_data_GReaT.to_csv('synthetic_data_german_GReaT.csv', index=False)

During synthetic data generation with the GReaT model (both GPT-2 and distil-GPT2 versions), we observe that some categorical columns occasionally contain values that deviate significantly from the original categories. In several cases, the generated entries include additional text or concatenated phrases that extend beyond the expected category labels. For example, the Sex or Saving accounts columns may contain full sentences appended to the original value.

This behavior is likely inherent to the language-model-based architecture of GReaT. Since the model is trained on sequences of tokenized text rather than discrete categorical labels, it can produce outputs that resemble natural language rather than strictly adhering to the original categories. While this allows for flexible and creative sampling, it can also generate artifacts that do not align perfectly with the expected tabular schema.

Such observations highlight a key difference between LLM-based synthetic data generation and traditional tabular generative models (e.g., CopulaGAN, TVAE, CTGAN), where outputs strictly respect the input categories. Awareness of this phenomenon is important when interpreting or using synthetic datasets produced by GReaT.