# Synthetic Data Generation on the Australian Credit Approval Dataset

## Introduction

In this notebook we focus on the generation of synthetic data by leveraging the models trained in the previous steps. Each trained model is loaded from its saved state and used to produce synthetic samples of the Australian Credit Approval dataset.

As in the previous case, these generated datasets will serve as the foundation for the upcoming evaluation phase.

## 0 Imports and function definition

In this notebook we import the libraries needed for data handling, loading trained models, and generating synthetic samples with the different generative approaches.

### Downloads

In [ ]:
!pip install be_great peft==0.9.0 sdv

Collecting be_great
  Downloading be_great-0.0.9-py3-none-any.whl.metadata (5.8 kB)
Collecting peft==0.9.0
  Downloading peft-0.9.0-py3-none-any.whl.metadata (13 kB)
Collecting sdv
  Downloading sdv-1.24.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (2.6.0+cu124)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (4.53.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (1.9.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (0.5.3)
Requirement already satisfied: huggingface-hub>=0.17.0 in /usr/local/lib/python3.11/dist-packages (from peft==0.9.0) (0.33.4)
Requirement already satisfied: datasets>=2.5.2 in /usr/local/lib/python3.11/dist-packages (from be_great) (2.14.4)
Requirement already satisfied: pandas>=1.4.4 in /usr/local/lib/python3.11/dist-packages (from be_great) (2.2.2)
Requirement already satisfied: scikit_learn>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from be_great) (1.6.1)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.39.11-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.39.11-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from sdv) (3.1.1)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from sdv) (0.21)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.12.3-py3-none-any.whl.metadata (9.5 kB)
Collecting ctgan>=0.11.0 (from sdv)
  Downloading ctgan-0.11.0-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting rdt>=1.17.0 (from sdv)
  Downloading rdt-1.17.1-py3-none-any.whl.metadata (10 kB)
Collecting sdmetrics>=0.21.0 (from sdv)
  Downloading sdmetrics-0.21.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.11/dist-packages (from sdv) (4.3.8)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.13.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.11/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.11/dist-packages (from copulas>=0.12.1->sdv) (1.16.0)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (0.3.7)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets>=2.5.2->be_great) (2025.7.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.5.2->be_great) (3.11.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (1.1.5)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.4->be_great) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.4->be_great) (2025.2)
Collecting Faker>=17 (from rdt>=1.17.0->sdv)
  Downloading faker-37.4.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn>=1.1.1->be_great) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn>=1.1.1->be_great) (3.6.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.13.0->peft==0.9.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->peft==0.9.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft==0.9.0) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers->peft==0.9.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers->peft==0.9.0) (0.21.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.5.2->be_great) (1.20.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (8.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets>=2.5.2->be_great) (2025.7.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.13.0->peft==0.9.0) (3.0.2)
Downloading peft-0.9.0-py3-none-any.whl (190 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 7.7 MB/s eta 0:00:00
Downloading be_great-0.0.9-py3-none-any.whl (19 kB)
Downloading sdv-1.24.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 18.1 MB/s eta 0:00:00
Downloading boto3-1.39.11-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 9.2 MB/s eta 0:00:00
Downloading botocore-1.39.11-py3-none-any.whl (13.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 121.3 MB/s eta 0:00:00
Downloading copulas-0.12.3-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.4 MB/s eta 0:00:00
Downloading ctgan-0.11.0-py3-none-any.whl (24 kB)
Downloading deepecho-0.7.0-py3-none-any.whl (27 kB)
Downloading rdt-1.17.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 8.1 MB/s eta 0:00:00
Downloading sdmetrics-0.21.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.5/193.5 kB 17.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 123.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 92.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 62.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 796.9 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 18.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.1 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.3 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 68.2 MB/s eta 0:00:00
Downloading faker-37.4.2-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 76.7 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.13.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.3/85.3 kB 8.7 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, jmespath, Faker, nvidia-cusparse-cu12, nvidia-cudnn-cu12, botocore, s3transfer, rdt, nvidia-cusolver-cu12, copulas, sdmetrics, boto3, deepecho, ctgan, sdv, peft, be_great
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: peft
    Found existing installation: peft 0.16.0
    Uninstalling peft-0.16.0:
      Successfully uninstalled peft-0.16.0
Successfully installed Faker-37.4.2 be_great-0.0.9 boto3-1.39.11 botocore-1.39.11 copulas-0.12.3 ctgan-0.11.0 deepecho-0.7.0 jmespath-1.0.1 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 peft-0.9.0 rdt-1.17.1 s3transfer-0.13.1 sdmetrics-0.21.0 sdv-1.24.1

### Imports

In [ ]:
import pandas as pd
import os
from be_great import GReaT
from sdv.single_table import TVAESynthesizer, CTGANSynthesizer, CopulaGANSynthesizer
from sdv.metadata import SingleTableMetadata
import pickle

In [ ]:
os.environ["WANDB_DISABLED"] = "true" #to avoid the requests from WANDB

### Functions definitions

In this notebook we reuse the same helper functions already introduced in the previous one, such as load_model for restoring trained models and the various create_synthetic_data_* functions for generating synthetic samples with each approach.

In [ ]:
def load_model(file_path):
  with(open(file_path, 'rb')) as f:
    model = pickle.load(f)
  return model

In [ ]:
def create_synthetic_data_CopulaGAN(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [ ]:
def create_synthetic_data_TVAE(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [ ]:
def create_synthetic_data_CTGAN(model, num_rows):
    synthetic_data = model.sample(num_rows=num_rows)
    return synthetic_data

In [ ]:
def create_synthetic_data_distil_GReaT(model, num_rows):
    synthetic_data = model.sample(n_samples=num_rows, max_length=2000)
    return synthetic_data

In [ ]:
def create_synthetic_data_GReaT(model, num_rows):
    synthetic_data = model.sample(n_samples=num_rows, max_length=2000)
    return synthetic_data

## 1 Sampling

In this phase we move to the sampling process, where we generate synthetic records using the previously defined functions. We set num_rows = 690, matching the size of the original dataset, in order to ensure fairness and comparability in the subsequent evaluation steps.

In [ ]:
num_rows = 690

### CopulaGAN

In [ ]:
model_CopulaGAN = load_model('copulagan_australian.pkl')

In [ ]:
synthetic_data_CopulaGAN = create_synthetic_data_CopulaGAN(model_CopulaGAN, num_rows)

In [ ]:
synthetic_data_CopulaGAN.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class
0,0,55.71,0.922,2,6,4,0.040,1,1,0.0,0,3,143.0,5413.0,0
1,1,32.18,0.107,2,1,1,0.043,0,1,5.0,0,1,304.0,2.0,0
2,1,20.99,24.346,1,10,4,2.791,0,0,0.0,0,1,274.0,535.0,0
3,1,20.47,7.552,2,2,4,0.041,0,0,0.0,1,2,0.0,2.0,0
4,0,28.14,12.665,2,13,4,0.040,1,1,0.0,0,2,0.0,786.0,0

In [ ]:
synthetic_data_CopulaGAN.to_csv('synthetic_data_australian_CopulaGAN.csv', index=False)

### TVAE

In [ ]:
model_TVAE = load_model('tvae_australian.pkl')

In [ ]:
synthetic_data_TVAE = create_synthetic_data_TVAE(model_TVAE, num_rows)

In [ ]:
synthetic_data_TVAE.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class
0,1,27.42,0.436,2,14,4,0.337,1,0,0.0,0,2,200.0,156.0,1
1,1,46.88,7.156,2,11,4,5.353,1,0,0.0,0,2,0.0,127.0,1
2,1,23.63,0.880,2,2,4,0.108,0,0,0.0,1,2,385.0,1.0,0
3,1,34.88,1.544,2,9,4,0.146,1,1,0.0,1,2,489.0,1.0,1
4,1,24.94,8.485,2,3,4,1.731,1,1,0.0,1,2,123.0,542.0,1

In [ ]:
synthetic_data_TVAE.to_csv('synthetic_data_australian_TVAE.csv', index=False)

### CTGAN

In [ ]:
model_CTGAN = load_model('ctgan_australian.pkl')

In [ ]:
synthetic_data_CTGAN = create_synthetic_data_CTGAN(model_CTGAN, num_rows)

In [ ]:
synthetic_data_CTGAN.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class
0,1,41.61,0.000,2,8,4,0.471,0,0,0.0,0,2,147.0,183.0,0
1,0,73.20,4.866,2,5,8,2.783,0,0,0.0,0,2,49.0,1047.0,0
2,0,20.59,1.566,2,9,4,0.336,1,0,1.0,1,2,249.0,573.0,1
3,1,23.58,1.132,2,11,4,3.359,0,0,0.0,1,2,265.0,694.0,0
4,1,29.44,3.976,1,1,4,0.000,0,0,0.0,0,2,70.0,3976.0,0

In [ ]:
synthetic_data_CTGAN.to_csv('synthetic_data_australian_CTGAN.csv', index=False)

### Distil-GReaT

In [ ]:
model_distil_GReaT = load_model('distil_GReaT_australian.pkl')

In [ ]:
synthetic_data_distil_GReaT = create_synthetic_data_distil_GReaT(model_distil_GReaT, num_rows)

  0%|          | 0/690 [00:00<?, ?it/s]The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
757it [00:10, 69.53it/s]

In [ ]:
synthetic_data_distil_GReaT.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class
0,1.0,22.00,11.000,2.0,8.0,4.0,0.000,1.0,0.0,0.0,1.0,2.0,0.0,1.0,1.0
1,0.0,19.42,1.040,2.0,6.0,4.0,0.085,1.0,0.0,0.0,0.0,2.0,260.0,1.0,1.0
2,1.0,23.50,0.585,2.0,14.0,4.0,0.125,1.0,1.0,2.0,0.0,2.0,160.0,501.0,1.0
3,1.0,25.67,0.000,1.0,4.0,4.0,0.500,0.0,0.0,0.0,0.0,2.0,0.0,69.0,0.0
4,1.0,17.33,0.000,2.0,8.0,4.0,0.085,0.0,0.0,0.0,0.0,2.0,80.0,1.0,0.0

In [ ]:
synthetic_data_distil_GReaT.to_csv('synthetic_data_australian_distil_GReaT.csv', index=False)

GReaT

In [ ]:
model_GReaT = load_model('GReaT_australian.pkl')

In [ ]:
synthetic_data_GReaT = create_synthetic_data_GReaT(model_GReaT, num_rows)

778it [00:15, 48.93it/s]

In [ ]:
synthetic_data_GReaT.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class
0,1.0,21.75,0.835,1.0,4.0,4.0,0.415,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0
1,1.0,21.25,11.750,2.0,8.0,4.0,0.000,1.0,0.0,0.0,1.0,2.0,0.0,1.0,1.0
2,0.0,30.75,0.585,1.0,1.0,1.0,0.000,0.0,0.0,0.0,0.0,2.0,160.0,1.0,0.0
3,1.0,28.75,1.000,1.0,9.0,4.0,2.000,0.0,0.0,0.0,1.0,2.0,100.0,1.0,1.0
4,1.0,25.67,1.290,2.0,11.0,8.0,1.000,1.0,0.0,0.0,0.0,2.0,200.0,1.0,1.0

In [ ]:
synthetic_data_GReaT.to_csv('synthetic_data_australian_GReaT.csv', index=False)

In this case, we no longer observe the presence of "out-of-context words" that appeared in the synthetic data generated with GReaT for the German Credit Risk dataset. This difference arises because all the columns in the Australian Credit Approval dataset are numerical: even the categorical features were originally encoded as numbers to preserve privacy. Unlike in the German dataset, where LLM-based models such as GReaT tended to generate extra text fragments due to their natural predisposition to produce free-form sequences, the numerical representation here prevents such anomalies. While this characteristic helps generative models produce cleaner and more consistent outputs, it also makes it harder for a human to directly assess the quality and coherence of the synthetic data, shifting the focus toward quantitative evaluation metrics.